### ISSUE TITLE
Nice to have first-time developer stuff #feature_request

### ISSUE THREAD

**Issue by Genkilabs** [manifoldco/grafton#49]
Just getting started as a provider, good stuff here.
Currently our team is looking at going through the process of reviewing and possibly building a provider app for the Manifold marketplace. I have a couple nice-to-haves I thought I'd make note of as I go.

1. It would be great to have a Homebrew package for the Debian OSX build.
2. Currently the `--version` seems to be hard coded to "dev" https://github.com/manifoldco/grafton/blob/1e28a9e869b48dac655036ebafcab3c1f970cd90/cmd/version.go#L9

**Comment by tim-speed** [comment]
Thanks for the feedback! I'll add this to our open internal issue for tracking build improvements.

**Comment by seriousben** [comment]
The version bug has been addressed since this issue was opened.

Regarding the Debian OSX build request, would it still be useful? Could you provide more info about your setup and what you mean by Debian OSX? Do you mean supporting homebrew on linux?

Closing this issue for now, but we can either re-open it or open another one for the Debian OSX build if still needed.
